function out = genRefTalkerROI(filename, talker)
%IMPORTFILE Import label data from text file and generate times
%identifying main talker activity (ROI)
%
%  OUT = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as an
%  array of ROI [s] identifying main talker activity
%
%  Example:
%  OUT = importfile("Triad1_Trial1_Dir_28 Apr 09 35 40.txt", 2);
%
%  See also READTABLE, CONVERTIMESTAMP
%
% Auto-generated by MATLAB on 08-Sep-2022 15:30:59
% Expanded by Alexander Kittel (DTU)

%% Input handling
dataLines = [1, Inf];

%% Set up the Import Options and read the txt file
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ["\t", " "];

% Specify column names and types
opts.VariableNames = ["onset", "offset", "talker"];
opts.VariableTypes = ['char', "char", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Import the data
tab = readtable(filename, opts);

%% Generate ROI table

% Extract onset and offset times of specific talker
out = [...
    convertROITimeStamp(...
    cell2mat(tab.onset(tab.talker==talker)))...
    convertROITimeStamp(...
    cell2mat(tab.offset(tab.talker==talker)))....
    ];
end